import { MovieDetailResponse } from "./movie.interface";

const mockMovies: MovieDetailResponse[] = [
    {
        backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
        id: 912649,
        title: "Venom: The Last Dance",
        original_title: "Venom: The Last Dance",
        overview: "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
        poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
        adult: false,
        original_language: "en",
        popularity: 12656.263,
        release_date: "2024-10-22",
        video: false,
        vote_average: 6.6,
        vote_count: 1127,
        belongs_to_collection: null,
        budget: 0,
        genres: [],
        homepage: null,
        imdb_id: null,
        origin_country: [],
        production_companies: [],
        production_countries: [],
        revenue: 0,
        runtime: null,
        spoken_languages: [],
        status: "",
        tagline: null
    },
    {
        backdrop_path: "/tmvbyMIv56hc03Mtgusj2koFWKj.jpg",
        id: 1138194,
        title: "Heretic",
        original_title: "Heretic",
        overview: "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
        poster_path: "/5HJqjCTcaE1TFwnNh3Dn21be2es.jpg",
        adult: false,
        original_language: "en",
        popularity: 200.766,
        release_date: "2024-10-31",
        video: false,
        vote_average: 7.1,
        vote_count: 148,
        belongs_to_collection: null,
        budget: 0,
        genres: [],
        homepage: null,
        imdb_id: null,
        origin_country: [],
        production_companies: [],
        production_countries: [],
        revenue: 0,
        runtime: null,
        spoken_languages: [],
        status: "",
        tagline: null
    },
    {
        backdrop_path: "/9Qq8InnodUYs8zdam8Zj967i6RO.jpg",
        id: 1106739,
        title: "Juror #2",
        original_title: "Juror #2",
        overview: "While serving as a juror in a high profile murder trial, family man Justin Kemp finds himself struggling with a serious moral dilemma…one he could use to sway the jury verdict and potentially convict—or free—the accused killer.",
        poster_path: "/ugQkpGajKFQ8eyOEhGheR0HfWQ.jpg",
        adult: false,
        original_language: "en",
        popularity: 574.153,
        release_date: "2024-10-30",
        video: false,
        vote_average: 6.982,
        vote_count: 580,
        belongs_to_collection: null,
        budget: 0,
        genres: [],
        homepage: null,
        imdb_id: null,
        origin_country: [],
        production_companies: [],
        production_countries: [],
        revenue: 0,
        runtime: null,
        spoken_languages: [],
        status: "",
        tagline: null
    }
];

export default mockMovies;